import os

en_dict = {
    # Homepage
    '臻至科技 Alpenglow Tek — 高能效邊緣 AI 運算架構創新者。設計超低功耗 AI 處理器、客製化 ASIC/SoC 及 FPGA 原型開發服務。': 'Alpenglow Tek — Innovator of high-efficiency edge AI computing architectures. Designing ultra-low power AI processors, custom ASIC/SoC, and providing FPGA prototyping services.',
    '首頁 | 臻至科技 Alpenglow Tek': 'Home | Alpenglow Tek',
    '讓 AI 在最有限的能量': 'Maximizing AI Value',
    '發揮最大價值': 'With Limited Energy',
    '從超低功耗 AI 晶片到全客製化 ASIC，再到 FPGA 快速原型驗證，': 'From ultra-low power AI chips to fully customized ASICs, and rapid FPGA prototyping,',
    '臻至科技提供從概念到量產的完整硬體解決方案。': 'Alpenglow Tek provides complete hardware solutions from concept to mass production.',
    '從工業感測、環境監控到消費終端，我們讓 AI 從雲端走向現場，在資源受限的環境中依然精準運作。': 'From industrial sensing and environmental monitoring to consumer devices, we bring AI from the cloud to the edge, operating precisely even in resource-constrained environments.',
    '探索解決方案': 'Explore Solutions',
    '三大核心技術能力': 'Three Core Capabilities',
    '超低功耗 AI 運算架構': 'Ultra-Low Power AI Architecture',
    '聚焦於資源受限環境下的運算效率最佳化，提升系統在功耗與效能之間的整體平衡。': 'Focusing on computing efficiency optimization in resource-constrained environments to enhance the overall balance between power and performance.',
    '一站式 ASIC 設計服務': 'One-Stop ASIC Design Services',
    '涵蓋前端設計、後端實作、FPGA 原型驗證與系統開發，提供完整且一致的設計流程。': 'Covering front-end design, back-end implementation, FPGA prototyping, and system development, providing a complete and consistent design flow.',
    '量產前 FPGA 原型平台': 'Pre-Production FPGA Prototyping',
    '透過 FPGA 驗證與模擬進行功能測試與效能評估，加速設計迭代並降低流片風險。': 'Conducting functional testing and performance evaluation through FPGA verification and simulation, accelerating design iterations and reducing tape-out risks.',
    '我們正在實現的事': 'What We Are Achieving',
    '半導體產業創新成果': 'Semiconductor Industry Innovations',
    '臻至科技半導體產業創新與升級成果': 'Alpenglow Tek Semiconductor Industry Innovation and Upgrade Achievements',
    '榮獲2026 IC設計類 新創及中小企業組 金牌': 'Awarded 2026 IC Design Category Gold Medal for Startups & SMEs',
    '決賽入圍': 'Finalist',
    '自眾多參賽團隊中脫穎而出，入選決賽前 10 強': 'Stood out from numerous participating teams, selected as top 10 finalists',
    '台大創創加速器計畫': 'NTU Garage Accelerator Program',
    '臻至科技入選2026台大車庫暨創創加速器計畫': 'Alpenglow Tek selected for 2026 NTU Garage & Accelerator Program',
    '新北創力坊加速器': 'New Taipei City InnoSquare Accelerator',
    '臻至科技入選2026新北市政府旗下新北創力坊加速器': 'Alpenglow Tek selected for 2026 New Taipei City Government InnoSquare Accelerator',
    
    # About Us
    '關於我們 About Us | 臻至科技 Alpenglow Tek': 'About Us | Alpenglow Tek',
    '臻至科技是一家專注於超低功耗邊緣 AI 的 IC 設計公司，致力於打造能在資源受限環境中穩定運作的智慧運算架構。': 'Alpenglow Tek is an IC design company focused on ultra-low power edge AI, dedicated to building intelligent computing architectures that operate stably in resource-constrained environments.',
    '我們是專注於超低功耗邊緣 AI 的 IC 設計公司，': 'We are an IC design company focused on ultra-low power edge AI,',
    '致力於打造能在資源受限環境中穩定運作的智慧運算架構。': 'dedicated to building intelligent computing architectures that operate stably in resource-constrained environments.',
    '臻至科技專注於開發新一代超低功耗邊緣 AI 運算技術，打造高效率的 AI 推論解決方案。': 'Alpenglow Tek focuses on developing next-generation ultra-low power edge AI computing technologies, creating highly efficient AI inference solutions.',
    '我們聚焦於功耗、延遲與系統效率之間的平衡，協助客戶將 AI 能力導入各類終端裝置，使智慧運算能夠真正落地於邊緣場景。': 'We focus on the balance between power consumption, latency, and system efficiency, helping customers integrate AI capabilities into various terminal devices, enabling intelligent computing to truly land in edge scenarios.',
    '目前，我們提供多元合作形式，包括 AI 處理器 IP、ASIC / SoC 設計整合，以及 FPGA 原型開發與系統驗證服務，加速產品從概念驗證到實際部署的落地進程。': 'Currently, we offer diverse cooperation models, including AI processor IP, ASIC/SoC design integration, and FPGA prototyping and system verification services, accelerating the product implementation process from concept validation to actual deployment.',
    '我們在解決的問題': 'The Problems We Solve',
    '隨著 AI 應用從雲端走向邊緣，越來越多場景需要即時反應、長時間運作與低功耗的智慧處理能力。': 'As AI applications move from the cloud to the edge, more scenarios require real-time response, long-term operation, and low-power intelligent processing capabilities.',
    '然而，傳統運算架構在資料搬移過程中消耗大量能量，導致功耗過高與延遲增加，難以應用於資源受限的裝置與環境。': 'However, traditional computing architectures consume massive energy during data movement, resulting in excessive power consumption and increased latency, making them difficult to apply in resource-constrained devices and environments.',
    '臻至科技致力於從架構層級優化運算方式，降低不必要的資料傳輸，讓 AI 能在更低功耗、更高效率的條件下穩定運作。': 'Alpenglow Tek is committed to optimizing computing methods at the architectural level, reducing unnecessary data transmission, and allowing AI to operate stably under lower power and higher efficiency conditions.',
    '解決邊緣 AI 的挑戰': 'Solving Edge AI Challenges',
    '我們的核心能力': 'Our Core Capabilities',
    '透過架構層級的優化設計，大幅降低資料搬移帶來的能耗，提升整體運算效率，讓 AI 更適合部署於邊緣裝置。': 'Through architecture-level optimization design, significantly reducing energy consumption from data movement, improving overall computing efficiency, and making AI more suitable for deployment on edge devices.',
    'ASIC / SoC 設計整合能力': 'ASIC / SoC Design Integration Capability',
    '具備從架構規劃、IP 整合到晶片實現的能力，協助客戶打造符合應用需求的專用 AI 晶片。': 'Equipped with capabilities from architectural planning and IP integration to chip realization, helping customers build dedicated AI chips that meet application requirements.',
    '透過 FPGA 快速實現 AI 演算法與系統架構，加速 PoC 驗證與產品開發流程。': 'Rapidly implementing AI algorithms and system architectures through FPGA, accelerating PoC verification and product development processes.',
    '我們如何與客戶合作': 'How We Work with Customers',
    '針對特定應用場景，快速建構可驗證的系統原型，加速產品決策與導入。': 'For specific application scenarios, quickly build verifiable system prototypes to accelerate product decisions and adoption.',
    'IP 授權與系統整合': 'IP Licensing & System Integration',
    '提供 AI 處理器 IP，並協助整合至客戶既有 SoC 或產品架構中。': 'Providing AI processor IP and assisting in integration into the customer’s existing SoC or product architecture.',
    '客製化 ASIC / 系統設計': 'Custom ASIC / System Design',
    '根據應用需求進行客製化設計，打造兼具效能與功耗優勢的專用解決方案。': 'Providing custom design based on application needs, creating dedicated solutions with performance and power advantages.',
    '我們重視與客戶的長期合作關係，從技術評估到產品落地，提供完整且可持續的支援。': 'We value long-term cooperation with customers, providing complete and sustainable support from technical evaluation to product implementation.',
    
    # Brand Story
    '品牌故事 Brand Story | 臻至科技 Alpenglow Tek': 'Brand Story | Alpenglow Tek',
    '臻至科技 Alpenglow Tek 品牌故事 — 山巔之光，點亮每一個關鍵瞬間。追光而行，臻至無限。': 'Alpenglow Tek Brand Story — The light at the mountain peak, illuminating every critical moment. Chasing the light, reaching the infinite.',
    '山巔之光，點亮每一個關鍵瞬間': 'The Light at the Mountain Peak, Illuminating Every Critical Moment',
    '追求更高效、更精準、更具可能性的技術未來。': 'Pursuing a more efficient, precise, and promising technological future.',
    '追光而行．臻至無限': 'Chasing the Light, Reaching the Infinite',
    'Alpenglow Lights the Impossible.': 'Alpenglow Lights the Impossible.',
    '品牌名稱由來': 'Origin of the Brand Name',
    '這個名字源自': 'The name originates from',
    'Alpenglow — 山巔之光': 'Alpenglow — The Light at the Mountain Peak',
    '，代表高山之巔在日出與日落時分閃耀的那道光芒——短暫卻深刻，象徵著在關鍵時刻發揮最大價值的力量。': ', representing the glow shining at the mountain peak during sunrise and sunset—brief yet profound, symbolizing the power to maximize value at critical moments.',
    'Alpen（高山）': 'Alpen (High Mountain)',
    '象徵持續突破邊界、追求卓越，': 'symbolizes continuously pushing boundaries and pursuing excellence,',
    'Glow（光芒）': 'Glow (Light)',
    '則代表在資源受限或充滿挑戰的環境中，依然能散發清晰、精準且具影響力的技術光輝。': 'represents emitting clear, precise, and impactful technological brilliance even in resource-constrained or challenging environments.',
    '我們的品牌概念與技術選擇，都是「在關鍵時刻發揮最大價值」這個信念的實踐。': 'Our brand concept and technological choices are the realization of the belief to "maximize value at critical moments."',
    '「臻至」的意義': 'The Meaning of "Alpenglow"',
    '臻至無限': 'Reaching the Infinite',
    '真摯': 'Sincere',
    '「臻」代表達到完美的境界；「至」代表抵達目標。': '"Alpenglow" represents reaching a state of perfection and arriving at the goal.',
    '代表我們對技術價值的理解：不只是追求強大，而是在對的時刻，發揮真正的影響力。': 'represents our understanding of technological value: not just pursuing power, but exerting true influence at the right moment.',
    '我們始終以一顆真摯赤誠的心，': 'We always maintain a sincere and genuine heart,',
    '認真鑽研技術；': 'diligently researching technology;',
    '也象徵對合作夥伴、客戶與每一項承諾的重視。': 'and it also symbolizes our emphasis on partners, customers, and every commitment.',
    '我們相信': 'We Believe',
    'AI 不該': 'AI Should Not Be',
    '只存在於': 'Confined to',
    '高功耗設備。': 'High-Power Devices.',
    '真正的挑戰，是在': 'The Real Challenge is',
    '資源受限': 'Resource-Constrained Environments',
    '下依然做到最好。': 'and Still Performing the Best.',
    '功耗，不該成為': 'Power Consumption Should Not Be',
    '智慧落地': 'the Bottleneck for',
    '的門檻。': 'Intelligent Implementation.',
    '微小，卻絕對關鍵。': 'Small, Yet Absolutely Critical.',
    '在邊緣 AI 的世界裡，功耗、效能與即時性經常彼此拉扯。我們致力於在這三者間找到最佳解。': 'In the world of Edge AI, power, performance, and real-time response often pull against each other. We are dedicated to finding the optimal solution among these three.',
    '臻至科技打造超低功耗的 AI 運算技術，讓智慧可以走入更小型、更受限、但更需要即時反應的場景。': 'Alpenglow Tek builds ultra-low power AI computing technologies, allowing intelligence to enter smaller, more constrained, yet real-time demanding scenarios.',
    '從 FPGA 原型驗證到 ASIC 落地，我們致力於將前瞻技術轉化為可實際部署的產品，在效能、功耗與系統穩定性之間取得最佳平衡。': 'From FPGA prototyping to ASIC implementation, we are dedicated to translating cutting-edge technologies into deployable products, striking the best balance between performance, power, and system stability.',
    '理念化為產品': 'Translating Ideas into Products',
    '技術突破': 'Technological Breakthroughs',
    '效能與功耗的平衡': 'Balancing Performance and Power',
    '產業合作': 'Industry Collaboration',
    
    # Custom ASIC
    '客製化 ASIC 設計服務 | 臻至科技 Alpenglow Tek': 'Custom ASIC Design Services | Alpenglow Tek',
    '臻至科技致力於提供高品質且具競爭力的 ASIC 設計服務，協助客戶將創新構想轉化為可量產的半導體產品。無論是低功耗邊緣 AI SoC 或客製化專用晶片，我們都能提供專業且可靠的技術支援。': 'Alpenglow Tek is committed to providing high-quality and competitive ASIC design services, helping customers translate innovative ideas into mass-producible semiconductor products. Whether it is a low-power edge AI SoC or a customized dedicated chip, we provide professional and reliable technical support.',
    '客製化 ASIC 設計服務': 'Custom ASIC Design Services',
    '從架構規劃到系統驗證的一站式晶片開發解決方案': 'A One-Stop Chip Development Solution from Architecture Planning to System Verification',
    '臻至科技提供專業的客製化 ASIC 設計服務，涵蓋從規格定義、RTL 設計、後端實作到系統驗證與量產前準備。我們結合低功耗 AI 加速器技術與完整的 IC 設計流程，協助客戶加速產品開發週期並降低整體開發風險。': 'Alpenglow Tek provides professional custom ASIC design services covering specification definition, RTL design, back-end implementation to system verification and pre-production preparation. We combine low-power AI accelerator technology with a complete IC design flow to help customers accelerate product development cycles and reduce overall development risks.',
    '服務項目': 'Service Offerings',
    '與客戶共同定義產品規格、系統架構與 IP 策略，確立設計目標與開發路徑。': 'Define product specifications, system architectures, and IP strategies with customers to establish design goals and development paths.',
    'ASIC / IP 設計服務': 'ASIC / IP Design Services',
    '提供完整的 RTL 設計與驗證服務，並進行邏輯合成與實體設計實作，確保設計品質與時程掌控。': 'Provide complete RTL design and verification services, perform logic synthesis and physical design implementation, ensuring design quality and schedule control.',
    'AI 加速前端資料處理層': 'AI Acceleration Front-End Data Processing Layer',
    '結合 ANIX NPU IP 與低功耗架構技術，協助客戶打造具競爭力的邊緣 AI SoC。': 'Combine ANIX NPU IP and low-power architecture technology to help customers build competitive edge AI SoCs.',
    'FPGA 原型驗證': 'FPGA Prototyping',
    '透過 FPGA 原型驗證與系統 Bring-up，縮短開發週期並提升流片成功率。': 'Shorten development cycles and improve tape-out success rates through FPGA prototyping and system bring-up.',
    'SoM 與原型驗證設計': 'SoM and Prototyping Design',
    '提供 EVB 設計、System Bring-up 與晶片驗證服務，協助客戶完成產品化與量產前準備。': 'Provide EVB design, system bring-up, and chip verification services to help customers complete productization and pre-production preparation.',
    '我們提供從需求規劃到系統驗證的一站式 ASIC 開發服務，確保設計品質與時程可控，並協助客戶順利完成從概念到量產的晶片開發。': 'We provide one-stop ASIC development services from requirements planning to system verification, ensuring design quality and controllable schedules, and assisting customers in successfully completing chip development from concept to mass production.',
    '核心優勢': 'Core Advantages',
    '超低功耗 AI 晶片專業能力': 'Ultra-Low Power AI Chip Expertise',
    '從架構設計到晶片實現，具備全流程經驗，能兼顧技術深度與產品落地需求。': 'From architectural design to chip realization, we have full-process experience, balancing technical depth with product deployment needs.',
    '完整 ASIC 設計流程': 'Complete ASIC Design Flow',
    '降低開發風險並加速產品上市': 'Reduce Development Risks and Accelerate Time-to-Market',
    '彈性合作與 IP 整合能力': 'Flexible Cooperation and IP Integration Capabilities',
    '支援客戶自有 IP 或第三方 IP 整合，並提供客製化設計與技術顧問服務。': 'Support the integration of customers\' own IPs or third-party IPs, providing custom design and technical consulting services.',
    '為客戶打造高效且可靠的晶片開發流程': 'Building Efficient and Reliable Chip Development Workflows for Customers',
    '客製化 ASIC 應用領域': 'Custom ASIC Application Areas',
    '客製化 ASIC': 'Custom ASIC',
    '專業的 ASIC 與矽智財 (IP) 設計服務': 'Professional ASIC and IP Design Services',
    '縮短設計開發與量產時程': 'Shorten Design, Development, and Mass Production Schedules',
    
    # FPGA PQC, FPGA Event Camera, FPGA RF, FPGA Preprocess
    'FPGA — 事件相機': 'FPGA — Event Camera',
    '事件相機：影像辨識解決方案 | FPGA | 臻至科技 Alpenglow Tek': 'Event Camera: Image Recognition Solutions | FPGA | Alpenglow Tek',
    '臻至科技結合事件相機系統整合能力與 FPGA 硬體加速技術，為高速感知與即時運算場景提供低延遲、高吞吐與低功耗的專業解決方案。': 'Alpenglow Tek combines event camera system integration capabilities with FPGA hardware acceleration technology to provide professional solutions with low latency, high throughput, and low power for high-speed perception and real-time computing scenarios.',
    '事件相機：影像辨識解決方案': 'Event Camera: Image Recognition Solutions',
    '讓高速動態世界，真正被即時捕捉': 'Making the High-Speed Dynamic World Truly Capturable in Real Time',
    '事件相機（Event-based Camera）是一種不同於傳統 RGB 相機的新型感測技術。': 'Event-based Cameras represent a novel sensing technology different from traditional RGB cameras.',
    '結合 FPGA 的強大平行處理與極低延遲特性，為邊緣 AI、機器人與高速工業檢測帶來革命性的感知能力。': 'Combined with FPGA\'s powerful parallel processing and extremely low latency characteristics, bringing revolutionary perception capabilities to edge AI, robotics, and high-speed industrial inspection.',
    '什麼是事件相機？': 'What is an Event Camera?',
    '傳統相機以固定幀率（例如\n                            30fps、60fps）持續擷取完整畫面，即使畫面中沒有變化，也會重複記錄大量冗餘資訊。而事件相機則採用「非同步事件驅動」機制，只有在畫素亮度發生變化時才輸出事件資料。': 'Traditional cameras continuously capture full frames at a fixed frame rate (e.g., 30fps, 60fps), repeatedly recording massive redundant information even when there is no change. In contrast, event cameras use an "asynchronous event-driven" mechanism, outputting event data only when pixel brightness changes.',
    '這種機制帶來三項關鍵特性：': 'This mechanism brings three key characteristics:',
    '超低延遲反應': 'Ultra-Low Latency Response',
    '極高動態範圍': 'Extremely High Dynamic Range',
    '低冗餘輸出': 'Low Redundancy Output',
    '微秒等級即時輸出': 'Microsecond-Level Real-Time Output',
    'Microsecond 等級的反應速度，遠超傳統幀率相機，適合需要即時感知的高速場景應用。': 'Microsecond-level response speed, far exceeding traditional frame-rate cameras, suitable for high-speed scenarios requiring real-time perception.',
    '動態範圍可達 120dB 以上，即使在強光或極暗環境下，也能穩定捕捉關鍵影像資訊。': 'Dynamic range up to over 120dB, stably capturing critical image information even in strong light or extremely dark environments.',
    '僅在畫素亮度發生變化時輸出資料，大幅減少冗餘資訊，降低後端處理負擔。': 'Outputs data only when pixel brightness changes, significantly reducing redundant information and backend processing load.',
    '為什麼事件相機必須搭配 FPGA？': 'Why Must Event Cameras be Paired with FPGA?',
    '事件相機輸出的資料並非傳統的二維矩陣影像，而是連續且非同步的「事件流」（Event Stream）。這類資料在處理時具有極高的吞吐量與嚴苛的即時性要求。': 'The data output by event cameras is not a traditional 2D matrix image, but a continuous and asynchronous "Event Stream". Processing such data requires extremely high throughput and stringent real-time requirements.',
    '如果將事件流直接交由 CPU 或 GPU 處理，會面臨以下瓶頸：': 'If the event stream is directly processed by a CPU or GPU, it will face the following bottlenecks:',
    '中斷負載過高': 'Excessive Interrupt Load',
    '記憶體頻寬瓶頸': 'Memory Bandwidth Bottlenecks',
    '峰值吞吐量不足': 'Insufficient Peak Throughput',
    '臻至科技的 FPGA 事件處理解決方案': 'Alpenglow Tek\'s FPGA Event Processing Solutions',
    '透過專用硬體資料路徑設計與高速事件流處理架構，我們成功實現微秒等級延遲反應與高吞吐穩定運作能力。': 'Through dedicated hardware data path design and high-speed event stream processing architecture, we have successfully achieved microsecond-level latency response and high-throughput stable operation.',
    '高吞吐事件分析': 'High-Throughput Event Analysis',
    '支援高速介面（PCIe、JESD204B/C、100GbE）': 'Supports High-Speed Interfaces (PCIe, JESD204B/C, 100GbE)',
    '極低延遲前處理能力': 'Ultra-Low Latency Preprocessing Capabilities',
    '邊緣偵測與特徵提取': 'Edge Detection & Feature Extraction',
    '光流 (Optical Flow) 與目標追蹤': 'Optical Flow & Target Tracking',
    '客製化 AI 感知加速模組': 'Customized AI Perception Acceleration Modules',
    '與傳統 RGB 相機的差異': 'Differences from Traditional RGB Cameras',
    '比較項目': 'Comparison Item',
    '傳統 RGB 相機': 'Traditional RGB Camera',
    '資料輸出': 'Data Output',
    '固定幀率完整畫面': 'Fixed Frame Rate Full Frame',
    '僅輸出變化事件': 'Outputs Only Changed Events',
    '延遲': 'Latency',
    '受限於幀率': 'Limited by Frame Rate',
    '極低': 'Extremely Low',
    '動態範圍': 'Dynamic Range',
    '有限': 'Limited',
    '極高': 'Extremely High',
    '資料量': 'Data Volume',
    '大量畫面資料': 'Massive Image Data',
    '相較之下較低': 'Comparatively Lower',
    '極端光照': 'Extreme Lighting',
    '容易過曝或欠曝': 'Prone to Overexposure/Underexposure',
    '可應對極端光照': 'Can Handle Extreme Lighting',
    '事件相機的產業應用': 'Industrial Applications of Event Cameras',
    '根據國際事件視覺技術發展趨勢，事件相機已廣泛應用於以下領域：': 'According to the development trends of international event vision technologies, event cameras have been widely used in the following areas:',
    '機器人與無人載具': 'Robotics & Unmanned Vehicles',
    '事件相機反應延遲低於 1ms，使機器人能在動態環境中做出即時判斷。': 'Event camera response latency below 1ms enables robots to make real-time judgments in dynamic environments.',
    '視覺導航與即時避障': 'Visual Navigation & Real-Time Obstacle Avoidance',
    '高速動作捕捉與追蹤': 'High-Speed Motion Capture & Tracking',
    '機械手臂精準定位與反應控制': 'Robotic Arm Precise Positioning & Response Control',
    '工業自動化與智慧製造': 'Industrial Automation & Smart Manufacturing',
    '超低延遲結合高動態範圍，可應對工業環境中的強光、陰影與高速運動挑戰。': 'Ultra-low latency combined with high dynamic range handles strong light, shadows, and high-speed motion challenges in industrial environments.',
    '高速生產線瑕疵即時偵測': 'Real-Time Defect Detection on High-Speed Production Lines',
    '高速旋轉元件與振動分析': 'High-Speed Rotating Components & Vibration Analysis',
    '晶片與電路板外觀檢驗': 'Chip & Circuit Board Appearance Inspection',
    '車用電子與智慧運輸': 'Automotive Electronics & Smart Transportation',
    '微秒級反應與高動態範圍感知，為智慧駕駛與 V2X 系統提供可靠的即時視覺支援。': 'Microsecond-level response and high dynamic range perception provide reliable real-time visual support for smart driving and V2X systems.',
    'ADAS 視覺感知前處理': 'ADAS Visual Perception Preprocessing',
    '駕駛員行為即時分析': 'Real-Time Driver Behavior Analysis',
    '高速道路目標偵測與追蹤': 'High-Speed Road Target Detection & Tracking',
    '智慧監控與安全應用': 'Smart Surveillance & Security Applications',
    '結合 FPGA 即時處理能力，事件相機可實現全天候監控與高可靠度國防感知。': 'Combined with FPGA real-time processing capabilities, event cameras enable all-weather surveillance and highly reliable defense perception.',
    '低功耗長時間夜視監控': 'Low-Power Long-Term Night Vision Surveillance',
    '邊境感知與無人機反制系統': 'Border Perception & Anti-Drone Systems',
    '夜間與惡劣天氣感知輔助': 'Night & Harsh Weather Perception Assistance',
    '臻至科技已完成事件相機與 FPGA 平台之整合與即時處理驗證。': 'Alpenglow Tek has completed the integration and real-time processing verification of event cameras and FPGA platforms.',
    '下方影片展示實際系統運行與事件處理成果。': 'The video below demonstrates actual system operation and event processing results.',
    '展示事件相機與 FPGA 系統整合之實際運作成果': 'Showcasing the actual operation results of Event Camera and FPGA system integration',
    '與我們合作，打造下一代智慧晶片': 'Partner with us to build next-generation smart chips',
    
    'FPGA — 視覺/聽覺前處理': 'FPGA — Vision/Audio Preprocessing',
    'FPGA – 視覺與聽覺前處理加速解決方案 | 臻至科技 Alpenglow Tek': 'FPGA – Vision & Audio Preprocessing Acceleration Solutions | Alpenglow Tek',
    '為即時 AI 感知系統打造高速前處理核心': 'Building High-Speed Preprocessing Cores for Real-Time AI Perception Systems',
    '臻至科技提供基於 FPGA 的視覺與聽覺前處理解決方案，透過硬體級平行運算與可重構架構，加速影像與聲音資料在進入 AI 模型前的關鍵處理流程。此技術能大幅降低系統延遲並提升運算效率，廣泛應用於機器人、自主移動載具、智慧監控、語音互動裝置與邊緣 AI 感知系統。': 'Alpenglow Tek provides FPGA-based vision and audio preprocessing solutions, using hardware-level parallel computing and reconfigurable architectures to accelerate key processing flows of image and sound data before entering AI models. This technology significantly reduces system latency and improves computing efficiency, widely used in robots, AMRs, smart surveillance, voice interactive devices, and edge AI perception systems.',
    '為什麼 AI 感知系統需要 FPGA 前處理？': 'Why do AI Perception Systems Need FPGA Preprocessing?',
    '在 AI 視覺與聽覺應用中，大量時間與運算資源消耗於資料前處理階段，例如影像轉換、降噪、特徵提取與訊號轉換。若僅依賴 CPU 或 GPU 進行處理，容易產生延遲與功耗瓶頸，影響即時反應能力。FPGA 能透過硬體平行化與管線化設計，在資料進入 AI 模型之前完成即時前處理，顯著降低延遲並提升整體系統效能。': 'In AI vision and audio applications, significant time and computing resources are consumed during the data preprocessing stage, such as image conversion, noise reduction, feature extraction, and signal conversion. Relying solely on a CPU or GPU for processing easily creates latency and power bottlenecks, affecting real-time response capabilities. FPGA can complete real-time preprocessing before data enters AI models through hardware parallelism and pipeline design, significantly reducing latency and improving overall system performance.',
    '影像擷取與格式轉換 (RAW、YUV、RGB)': 'Image Capture & Format Conversion (RAW, YUV, RGB)',
    '影像縮放與幾何校正': 'Image Scaling & Geometric Correction',
    '去噪與影像增強 (Denoise、HDR)': 'Denoising & Image Enhancement (Denoise, HDR)',
    '聽覺前處理技術': 'Audio Preprocessing Technology',
    '語音擷取與降噪處理': 'Voice Capture & Noise Reduction',
    '回聲消除 (AEC) 與波束成形 (Beamforming)': 'Acoustic Echo Cancellation (AEC) & Beamforming',
    'FFT／頻譜分析與特徵提取 (MFCC)': 'FFT / Spectrum Analysis & Feature Extraction (MFCC)',
    '聲源定位 (Sound Source Localization)': 'Sound Source Localization',
    '語音活動偵測 (VAD)': 'Voice Activity Detection (VAD)',
    '降低主處理器負載': 'Reduce Main Processor Load',
    'AI 前處理管線設計與優化': 'AI Preprocessing Pipeline Design & Optimization',
    '感測器介面整合 (Camera / Microphone)': 'Sensor Interface Integration (Camera / Microphone)',
    '邊緣 AI 落地場景': 'Edge AI Implementation Scenarios',
    '自主移動機器人 (AMR) 與服務型機器人': 'Autonomous Mobile Robots (AMR) & Service Robots',
    '多感測器融合與低延遲感知': 'Multi-Sensor Fusion & Low-Latency Perception',
    '即時影像分析與目標辨識': 'Real-Time Image Analysis & Target Recognition',
    '語音互動與人機協作': 'Voice Interaction & Human-Machine Collaboration',
    '以極低延遲的硬體加速，打造即時 AI 感知系統': 'Building real-time AI perception systems with ultra-low latency hardware acceleration',
    
    'FPGA — PQC 密碼學': 'FPGA — PQC Cryptography',
    '透過平行化資料路徑與管線化設計，大幅降低加解密延遲並提升系統整體吞吐量，適用於即時安全通訊與高效能應用。': 'Through parallelized data paths and pipeline design, significantly reducing encryption/decryption latency and increasing overall system throughput, suitable for real-time secure communication and high-performance applications.',
    '高安全數位簽章、身分驗證與交易保護。': 'High-security digital signatures, identity verification, and transaction protection.',
    '支援演算法更新與標準演進，當 PQC 標準持續發展時，可透過重新配置 FPGA 快速升級，降低系統風險與維運成本。': 'Supporting algorithm updates and standard evolution, as PQC standards continue to develop, quick upgrades via FPGA reconfiguration reduce system risks and maintenance costs.',
    '針對 PQC 演算法中的多項式運算、模數運算與 NTT（Number Theoretic Transform）進行專用硬體優化，顯著提升運算效率。': 'Dedicated hardware optimization for polynomial arithmetic, modular arithmetic, and NTT (Number Theoretic Transform) in PQC algorithms, significantly improving computing efficiency.',
    'PQC 演算法（如 CRYSTALS-Kyber、CRYSTALS-Dilithium 等）具有高度運算密集與記憶體存取需求，若在傳統 CPU 或 GPU 上執行，往往面臨延遲高、功耗大與效率不足等問題。由於 CPU 與 GPU 的硬體架構固定且通用性高，難以針對特定密碼學運算進行最佳化。': 'PQC algorithms (e.g., CRYSTALS-Kyber, CRYSTALS-Dilithium) are highly compute-intensive and memory-access intensive. Executing them on traditional CPUs or GPUs often results in high latency, large power consumption, and inefficiency. Since CPU and GPU hardware architectures are fixed and highly generalized, they are difficult to optimize for specific cryptographic operations.',
    '相較之下，FPGA 具備可重組（Reconfigurable）特性，可依據 PQC 演算法需求客製化硬體架構，透過高度平行化運算與專用資料通道設計，在更低的資源使用下實現更低的延遲與更低的功耗，並兼具靈活性與可升級能力。': 'In contrast, FPGA features reconfigurability, allowing custom hardware architectures based on PQC algorithm requirements. Through highly parallelized computing and dedicated data path design, it achieves lower latency and lower power consumption with fewer resources, balancing flexibility and upgradeability.',
    '透過實際 FPGA 平台展示，我們呈現後量子密碼學演算法的硬體加速成果與系統整合能力，展現高效能、低延遲與低功耗的技術優勢。': 'Through actual FPGA platform demonstrations, we present the hardware acceleration results and system integration capabilities of post-quantum cryptographic algorithms, demonstrating the technical advantages of high performance, low latency, and low power consumption.',
    '探索臻至科技在後量子密碼學硬體加速領域的技術成果與實際系統驗證': 'Explore Alpenglow Tek\'s technical achievements and actual system verification in the field of post-quantum cryptography hardware acceleration',
    
    'FPGA — RF 射頻': 'FPGA — RF Radio Frequency',
    'FPGA – RF 射頻高速訊號處理解決方案 | 臻至科技 Alpenglow Tek': 'FPGA – RF High-Speed Signal Processing Solutions | Alpenglow Tek',
    '臻至科技提供基於 FPGA 的 RF 射頻訊號處理解決方案，即時處理高速、高頻寬的無線訊號，廣泛應用於 5G/6G 通訊、雷達系統、衛星通訊與電子戰設備。': 'Alpenglow Tek provides FPGA-based RF signal processing solutions to process high-speed, high-bandwidth wireless signals in real time, widely used in 5G/6G communications, radar systems, satellite communications, and electronic warfare equipment.',
    '為新世代無線通訊打造高效能 RF 訊號處理核心': 'Building High-Performance RF Signal Processing Cores for Next-Generation Wireless Communications',
    '臻至科技提供基於 FPGA 的 RF 射頻訊號處理解決方案，能即時處理高速、高頻寬的無線訊號，廣泛應用於 5G/6G 通訊、雷達系統、衛星通訊與電子戰設備，協助客戶實現高效能、低延遲與高度彈性的系統設計。': 'Alpenglow Tek provides FPGA-based RF signal processing solutions that can process high-speed, high-bandwidth wireless signals in real time. These solutions are widely used in 5G/6G communications, radar systems, satellite communications, and electronic warfare equipment, helping customers achieve high-performance, low-latency, and highly flexible system designs.',
    '為什麼 RF 射頻系統需要 FPGA？': 'Why do RF Systems Need FPGA?',
    'RF 射頻系統需處理高速、高頻寬且即時性的資料流，對延遲、吞吐量與運算效率要求極高。': 'RF systems need to process high-speed, high-bandwidth, and real-time data streams, with extremely high demands on latency, throughput, and computing efficiency.',
    'FPGA 憑藉其可重構與高度平行化架構，成為 RF 與無線通訊系統的理想運算平台。': 'Relying on its reconfigurable and highly parallelized architecture, FPGA has become the ideal computing platform for RF and wireless communication systems.',
    'CPU/GPU vs. FPGA：RF 訊號處理平台比較': 'CPU/GPU vs. FPGA: RF Signal Processing Platform Comparison',
    '即時處理能力': 'Real-Time Processing Capability',
    '中斷負載過高，延遲較高': 'Excessive interrupt load, higher latency',
    '硬體級即時處理能力': 'Hardware-level real-time processing capability',
    '平行處理能力': 'Parallel Processing Capability',
    '受限於核心數量': 'Limited by the number of cores',
    '高度平行化運算架構': 'Highly parallelized computing architecture',
    '功耗效率': 'Power Efficiency',
    '較高': 'Higher',
    '較低': 'Lower',
    '可客製化程度': 'Customizability',
    '無': 'None',
    '有': 'Yes',
    '臻至科技 FPGA RF 射頻訊號處理解決方案': 'Alpenglow Tek FPGA RF Signal Processing Solutions',
    'RF 數位前端（DFE）設計': 'RF Digital Front-End (DFE) Design',
    '數位下變頻（DDC）與上變頻（DUC）': 'Digital Down-Conversion (DDC) & Up-Conversion (DUC)',
    '數位濾波器設計（FIR / CIC）': 'Digital Filter Design (FIR / CIC)',
    'FPGA 頻譜分析與訊號處理': 'FPGA Spectrum Analysis & Signal Processing',
    'FFT / IFFT 頻譜分析': 'FFT / IFFT Spectrum Analysis',
    '調變與解調技術': 'Modulation & Demodulation Technology',
    '雷達訊號處理加速': 'Radar Signal Processing Acceleration',
    '多通道同步處理': 'Multi-Channel Synchronous Processing',
    '適用於 SDR（Software-Defined Radio）': 'Suitable for SDR (Software-Defined Radio)',
    'SDR 平台開發與客製化': 'SDR Platform Development & Customization',
    'FPGA 解碼平行處理': 'FPGA Decoding Parallel Processing',
    '5G/6G 與無線通訊': '5G/6G & Wireless Communications',
    '基地台與小型基地台': 'Base Stations & Small Cells',
    'Open RAN 架構': 'Open RAN Architecture',
    'Massive MIMO 與 Beamforming': 'Massive MIMO & Beamforming',
    '無線回傳與前傳': 'Wireless Backhaul & Fronthaul',
    '雷達與感測系統': 'Radar & Sensing Systems',
    '車用毫米波雷達': 'Automotive mmWave Radar',
    '國防雷達與電子戰': 'Defense Radar & Electronic Warfare',
    '無人機與航太感測': 'Drone & Aerospace Sensing',
    '衛星與航太通訊': 'Satellite & Aerospace Communications',
    '低軌道衛星（LEO）': 'Low Earth Orbit (LEO) Satellites',
    '衛星地面站': 'Satellite Ground Stations',
    '深空通訊': 'Deep Space Communications',
    '測試與量測設備': 'Test & Measurement Equipment',
    '頻譜分析儀': 'Spectrum Analyzers',
    '訊號產生器': 'Signal Generators',
    'EMI/EMC 測試系統': 'EMI/EMC Testing Systems',
    'RF 測試平台': 'RF Testing Platforms',
    '為新世代無線通訊與雷達系統提供高效能、低延遲的可重構運算平台': 'Providing High-Performance, Low-Latency Reconfigurable Computing Platforms for Next-Generation Wireless Communications and Radar Systems',
    '在無線通訊與雷達系統中，產品競爭的關鍵不僅在於頻寬與運算能力，更在於即時性、可靠度與系統彈性。臻至科技透過 FPGA 可重構運算架構與高速數位訊號處理技術，提供低延遲、高吞吐與高可靠度的 RF 射頻解決方案，協助客戶加速產品開發並實現新世代通訊與感測系統的創新應用。': 'In wireless communications and radar systems, product competitiveness lies not only in bandwidth and computing power but also in real-time response, reliability, and system flexibility. Through FPGA reconfigurable computing architectures and high-speed digital signal processing technology, Alpenglow Tek provides low-latency, high-throughput, and highly reliable RF solutions, helping customers accelerate product development and achieve innovative applications in next-generation communication and sensing systems.',
    '臻至科技具備高速數位訊號處理與 FPGA 設計專業，提供完整的 RF 射頻訊號處理解決方案，協助客戶快速實現高效能無線通訊與雷達系統。': 'Alpenglow Tek has high-speed digital signal processing and FPGA design expertise, providing complete RF signal processing solutions to help customers quickly implement high-performance wireless communication and radar systems.',

    # News
    '掌握臻至科技的最新動態與媒體報導，我們致力於超低功耗邊緣 AI 運算技術創新。': 'Keep up with the latest updates and media coverage of Alpenglow Tek as we drive innovation in ultra-low power edge AI computing technology.',
    '第二屆「智慧創新大賞」百大贏家出爐': 'The Top 100 Winners of the 2nd "Smart Innovation Awards" Announced',
    '經濟部 產業技術司': 'Department of Industrial Technology, MOEA',
    '國立台灣大學 TEC': 'National Taiwan University TEC',
    '國家高速網路與計算中心': 'National Center for High-performance Computing',
    '新北市青年局-新北創力坊': 'New Taipei City Youth Bureau - InnoSquare',
    '延伸閱讀': 'Further Reading',
    
    # Team
    '擁有 20 年以上業界產品經驗，專注於領導企業在 IC 設計領域的創新發展，並推動公司在高效能計算及自訂硬體加速解決方案方面的佈局': 'Over 20 years of industry product experience, focusing on leading corporate innovation in IC design and driving the company\'s presence in high-performance computing and custom hardware acceleration solutions.',
    '專注於客戶關係維護與業務拓展，負責FPGA IP授權、技術服務合約談判，開拓新市場機會，並推動產官學合作與策略夥伴關係發展': 'Focuses on customer relationship maintenance and business expansion, responsible for FPGA IP licensing, technical service contract negotiation, exploring new market opportunities, and promoting industry-academia collaboration and strategic partnerships.',
    '擁有深厚業界IC設計專案經驗、多項硬體加速器專利與頂尖論壇發表論文，專注於硬體加速和嵌入式系統設計，領導團隊在硬體加速領域的持續創新與優化': 'Possesses profound industry IC design project experience, multiple hardware accelerator patents, and top forum published papers. Focuses on hardware acceleration and embedded system design, leading the team in continuous innovation and optimization in the hardware acceleration field.',
    '專注於系統性能優化與維護，並協助設計與實現 ASIC 解決方案，確保產品在硬體層面的穩定性、高效能與整體整合品質。': 'Focuses on system performance optimization and maintenance, and assists in designing and implementing ASIC solutions to ensure product stability, high performance, and overall integration quality at the hardware level.',
    '負責分析市場數據、產業趨勢與競品動態，根據研究結果提出策略建議，並參與投資評估、合作洽談、商務開發及相關商業決策。': 'Responsible for analyzing market data, industry trends, and competitor dynamics, proposing strategic recommendations based on research results, and participating in investment evaluation, cooperation negotiations, business development, and related business decisions.',
    '團隊來自頂尖電資與商管系所，並具備 IC 設計、系統架構與 AI 應用領域的實務經驗，涵蓋從演算法理解、硬體架構設計到晶片實現與系統整合的完整能力。': 'The team comes from top electrical engineering, computer science, and business management departments, and has practical experience in IC design, system architecture, and AI application fields, covering complete capabilities from algorithm understanding and hardware architecture design to chip implementation and system integration.',
    '從架構設計到晶片實現，具備全流程經驗，能兼顧技術深度與產品落地需求。': 'From architectural design to chip realization, we have full-process experience, balancing technical depth with product deployment needs.',
    '結合工程、系統與市場能力，讓技術開發與應用拓展能同步前進。': 'Combining engineering, system, and market capabilities, enabling technology development and application expansion to advance simultaneously.',
    '我們相信，好的技術來自跨領域的協作、開放的討論與彼此信任。在專業分工之外，我們也重視平等交流與共同成長，持續打造一支能面對挑戰、也能一起前進的團隊。': 'We believe that good technology comes from cross-disciplinary collaboration, open discussion, and mutual trust. Beyond professional division of labor, we also value equal communication and mutual growth, continuously building a team capable of facing challenges and moving forward together.'
}

ja_dict = {
    # Homepage
    '臻至科技 Alpenglow Tek — 高能效邊緣 AI 運算架構創新者。設計超低功耗 AI 處理器、客製化 ASIC/SoC 及 FPGA 原型開發服務。': 'Alpenglow Tek — 高効率エッジAIコンピューティングアーキテクチャのイノベーター。超低消費電力AIプロセッサ、カスタムASIC/SoC、FPGAプロトタイピングサービスの設計。',
    '首頁 | 臻至科技 Alpenglow Tek': 'ホーム | Alpenglow Tek',
    '讓 AI 在最有限的能量': '限られたエネルギーで',
    '發揮最大價值': 'AIの価値を最大化',
    '從超低功耗 AI 晶片到全客製化 ASIC，再到 FPGA 快速原型驗證，': '超低消費電力AIチップからフルカスタムASIC、迅速なFPGAプロトタイピングまで、',
    '臻至科技提供從概念到量產的完整硬體解決方案。': 'Alpenglow Tekは概念から量産までの完全なハードウェアソリューションを提供します。',
    '從工業感測、環境監控到消費終端，我們讓 AI 從雲端走向現場，在資源受限的環境中依然精準運作。': '産業用センシングや環境モニタリングからコンシューマ端末まで、私たちはAIをクラウドから現場へと導き、リソースが制限された環境でも正確に機能させます。',
    '探索解決方案': 'ソリューションを探す',
    '三大核心技術能力': '3つのコア技術能力',
    '超低功耗 AI 運算架構': '超低消費電力AIアーキテクチャ',
    '聚焦於資源受限環境下的運算效率最佳化，提升系統在功耗與效能之間的整體平衡。': 'リソース制約環境下での計算効率最適化に焦点を当て、消費電力とパフォーマンスの全体的なバランスを向上させます。',
    '一站式 ASIC 設計服務': 'ワンストップASIC設計サービス',
    '涵蓋前端設計、後端實作、FPGA 原型驗證與系統開發，提供完整且一致的設計流程。': 'フロントエンド設計、バックエンド実装、FPGAプロトタイピング、システム開発を網羅し、完全で一貫した設計フローを提供します。',
    '量產前 FPGA 原型平台': '量産前FPGAプロトタイププラットフォーム',
    '透過 FPGA 驗證與模擬進行功能測試與效能評估，加速設計迭代並降低流片風險。': 'FPGA検証とシミュレーションによる機能テストとパフォーマンス評価を行い、設計の反復を加速し、テープアウトのリスクを軽減します。',
    '我們正在實現的事': '私たちが実現していること',
    '半導體產業創新成果': '半導体産業のイノベーション成果',
    '臻至科技半導體產業創新與升級成果': 'Alpenglow Tek半導体産業の革新とアップグレードの成果',
    '榮獲2026 IC設計類 新創及中小企業組 金牌': '2026年IC設計カテゴリー スタートアップおよび中小企業部門 金賞受賞',
    '決賽入圍': 'ファイナリスト',
    '自眾多參賽團隊中脫穎而出，入選決賽前 10 強': '多数の参加チームから際立ち、トップ10のファイナリストに選出',
    '台大創創加速器計畫': '台湾大学イノベーションアクセラレータープログラム',
    '臻至科技入選2026台大車庫暨創創加速器計畫': 'Alpenglow Tek、2026年台湾大学ガレージ＆アクセラレータープログラムに選出',
    '新北創力坊加速器': '新北市InnoSquareアクセラレーター',
    '臻至科技入選2026新北市政府旗下新北創力坊加速器': 'Alpenglow Tek、2026年新北市政府InnoSquareアクセラレーターに選出',

    # About Us
    '關於我們 About Us | 臻至科技 Alpenglow Tek': '私たちについて | Alpenglow Tek',
    '臻至科技是一家專注於超低功耗邊緣 AI 的 IC 設計公司，致力於打造能在資源受限環境中穩定運作的智慧運算架構。': 'Alpenglow Tekは超低消費電力エッジAIに特化したIC設計会社であり、リソース制約環境で安定して動作するインテリジェントコンピューティングアーキテクチャの構築に取り組んでいます。',
    '我們是專注於超低功耗邊緣 AI 的 IC 設計公司，': '私たちは超低消費電力エッジAIに特化したIC設計会社であり、',
    '致力於打造能在資源受限環境中穩定運作的智慧運算架構。': 'リソース制約環境で安定して動作するインテリジェントコンピューティングアーキテクチャの構築に取り組んでいます。',
    '臻至科技專注於開發新一代超低功耗邊緣 AI 運算技術，打造高效率的 AI 推論解決方案。': 'Alpenglow Tekは次世代超低消費電力エッジAIコンピューティング技術の開発に注力し、高効率なAI推論ソリューションを構築しています。',
    '我們聚焦於功耗、延遲與系統效率之間的平衡，協助客戶將 AI 能力導入各類終端裝置，使智慧運算能夠真正落地於邊緣場景。': '私たちは消費電力、レイテンシ、システム効率のバランスに焦点を当て、お客様がAI能力を様々な端末デバイスに導入し、インテリジェントコンピューティングがエッジシナリオで真に実装されるよう支援します。',
    '目前，我們提供多元合作形式，包括 AI 處理器 IP、ASIC / SoC 設計整合，以及 FPGA 原型開發與系統驗證服務，加速產品從概念驗證到實際部署的落地進程。': '現在、私たちはAIプロセッサIP、ASIC/SoC設計統合、FPGAプロトタイピングおよびシステム検証サービスを含む多様な協力モデルを提供し、概念実証から実際の展開までの製品実装プロセスを加速しています。',
    '我們在解決的問題': '私たちが解決する課題',
    '隨著 AI 應用從雲端走向邊緣，越來越多場景需要即時反應、長時間運作與低功耗的智慧處理能力。': 'AIアプリケーションがクラウドからエッジに移行するにつれ、リアルタイムの応答、長時間の動作、低消費電力のインテリジェント処理能力を必要とするシナリオが増えています。',
    '然而，傳統運算架構在資料搬移過程中消耗大量能量，導致功耗過高與延遲增加，難以應用於資源受限的裝置與環境。': 'しかし、従来のコンピューティングアーキテクチャはデータ移動中に大量のエネルギーを消費し、過剰な消費電力と遅延の増加をもたらし、リソースが制限されたデバイスや環境での適用を困難にしています。',
    '臻至科技致力於從架構層級優化運算方式，降低不必要的資料傳輸，讓 AI 能在更低功耗、更高效率的條件下穩定運作。': 'Alpenglow Tekはアーキテクチャレベルでの計算方法の最適化に取り組んでおり、不要なデータ転送を減らし、AIがより低い消費電力と高い効率で安定して動作できるようにしています。',
    '解決邊緣 AI 的挑戰': 'エッジAIの課題解決',
    '我們的核心能力': '私たちのコアコンピタンス',
    '透過架構層級的優化設計，大幅降低資料搬移帶來的能耗，提升整體運算效率，讓 AI 更適合部署於邊緣裝置。': 'アーキテクチャレベルの最適化設計により、データ移動によるエネルギー消費を大幅に削減し、全体的な計算効率を向上させ、AIをエッジデバイスへの展開により適したものにします。',
    'ASIC / SoC 設計整合能力': 'ASIC / SoC 設計統合能力',
    '具備從架構規劃、IP 整合到晶片實現的能力，協助客戶打造符合應用需求的專用 AI 晶片。': 'アーキテクチャ計画やIP統合からチップの実現までの能力を備え、お客様がアプリケーション要件を満たす専用AIチップを構築できるよう支援します。',
    '透過 FPGA 快速實現 AI 演算法與系統架構，加速 PoC 驗證與產品開發流程。': 'FPGAを通じてAIアルゴリズムとシステムアーキテクチャを迅速に実装し、PoC検証と製品開発プロセスを加速します。',
    '我們如何與客戶合作': 'お客様との協力方法',
    '針對特定應用場景，快速建構可驗證的系統原型，加速產品決策與導入。': '特定のアプリケーションシナリオ向けに検証可能なシステムプロトタイプを迅速に構築し、製品の意思決定と導入を加速します。',
    'IP 授權與系統整合': 'IPライセンスとシステム統合',
    '提供 AI 處理器 IP，並協助整合至客戶既有 SoC 或產品架構中。': 'AIプロセッサIPを提供し、お客様の既存のSoCまたは製品アーキテクチャへの統合を支援します。',
    '客製化 ASIC / 系統設計': 'カスタムASIC / システム設計',
    '根據應用需求進行客製化設計，打造兼具效能與功耗優勢的專用解決方案。': 'アプリケーション要件に基づくカスタム設計を提供し、性能と消費電力の優位性を兼ね備えた専用ソリューションを構築します。',
    '我們重視與客戶的長期合作關係，從技術評估到產品落地，提供完整且可持續的支援。': '私たちはお客様との長期的な協力関係を重視し、技術評価から製品の実装まで、完全で持続可能なサポートを提供します。',
    
    # Brand Story
    '品牌故事 Brand Story | 臻至科技 Alpenglow Tek': 'ブランドストーリー | Alpenglow Tek',
    '臻至科技 Alpenglow Tek 品牌故事 — 山巔之光，點亮每一個關鍵瞬間。追光而行，臻至無限。': 'Alpenglow Tekブランドストーリー — 山頂の光、あらゆる重要な瞬間を照らす。光を追い、無限へと至る。',
    '山巔之光，點亮每一個關鍵瞬間': '山頂の光、あらゆる重要な瞬間を照らす',
    '追求更高效、更精準、更具可能性的技術未來。': 'より効率的で、より正確で、可能性に満ちた技術の未来を追求します。',
    '追光而行．臻至無限': '光を追い、無限へと至る',
    'Alpenglow Lights the Impossible.': 'Alpenglow Lights the Impossible.',
    '品牌名稱由來': 'ブランド名の由来',
    '這個名字源自': 'この名前は、',
    'Alpenglow — 山巔之光': 'Alpenglow — 山頂の光',
    '，代表高山之巔在日出與日落時分閃耀的那道光芒——短暫卻深刻，象徵著在關鍵時刻發揮最大價值的力量。': 'に由来し、日の出と日没時に山頂で輝く光—短くも深く、重要な瞬間に最大の価値を発揮する力を象徴しています。',
    'Alpen（高山）': 'Alpen（高山）',
    '象徵持續突破邊界、追求卓越，': 'は継続的な境界の突破と卓越性の追求を象徴し、',
    'Glow（光芒）': 'Glow（光）',
    '則代表在資源受限或充滿挑戰的環境中，依然能散發清晰、精準且具影響力的技術光輝。': 'はリソースが制限された環境や困難な環境でも、明確で正確かつ影響力のある技術的輝きを放ち続けることを表しています。',
    '我們的品牌概念與技術選擇，都是「在關鍵時刻發揮最大價值」這個信念的實踐。': '私たちのブランドコンセプトと技術の選択はすべて、「重要な瞬間に最大の価値を発揮する」という信念の実践です。',
    '「臻至」的意義': '「臻至（Alpenglow）」の意味',
    '臻至無限': '無限へと至る',
    '真摯': '真摯',
    '「臻」代表達到完美的境界；「至」代表抵達目標。': '「臻」は完璧な境地に達することを表し、「至」は目標に到達することを表します。',
    '代表我們對技術價值的理解：不只是追求強大，而是在對的時刻，發揮真正的影響力。': 'は技術の価値に対する私たちの理解を表しています：ただ強さを追求するだけでなく、適切な瞬間に真の影響力を発揮すること。',
    '我們始終以一顆真摯赤誠的心，': '私たちは常に真摯で誠実な心を持ち、',
    '認真鑽研技術；': '技術を熱心に研究します；',
    '也象徵對合作夥伴、客戶與每一項承諾的重視。': 'そして、パートナー、顧客、あらゆる約束を重視することも象徴しています。',
    '我們相信': '私たちが信じること',
    'AI 不該': 'AIは',
    '只存在於': 'に限定されるべきではない',
    '高功耗設備。': '高消費電力デバイス',
    '真正的挑戰，是在': '真の課題は、',
    '資源受限': 'リソース制約環境',
    '下依然做到最好。': 'でも最高のパフォーマンスを発揮すること。',
    '功耗，不該成為': '消費電力は',
    '智慧落地': 'インテリジェントな実装の',
    '的門檻。': '障壁になるべきではない。',
    '微小，卻絕對關鍵。': '小さいが、絶対に重要。',
    '在邊緣 AI 的世界裡，功耗、效能與即時性經常彼此拉扯。我們致力於在這三者間找到最佳解。': 'エッジAIの世界では、消費電力、性能、リアルタイムの応答がしばしば相反します。私たちはこれら3つの最適な解決策を見つけることに取り組んでいます。',
    '臻至科技打造超低功耗的 AI 運算技術，讓智慧可以走入更小型、更受限、但更需要即時反應的場景。': 'Alpenglow Tekは超低消費電力AIコンピューティング技術を構築し、より小型で、より制限されているが、よりリアルタイムの反応が必要なシナリオにインテリジェンスをもたらします。',
    '從 FPGA 原型驗證到 ASIC 落地，我們致力於將前瞻技術轉化為可實際部署的產品，在效能、功耗與系統穩定性之間取得最佳平衡。': 'FPGAプロトタイピングからASIC実装まで、私たちは最先端技術を実際に展開可能な製品に変換し、性能、消費電力、システム安定性の最良のバランスを達成することに取り組んでいます。',
    '理念化為產品': 'アイデアを製品へ',
    '技術突破': '技術的ブレークスルー',
    '效能與功耗的平衡': '性能と消費電力のバランス',
    '產業合作': '産業連携',

    # Custom ASIC
    '客製化 ASIC 設計服務 | 臻至科技 Alpenglow Tek': 'カスタムASIC設計サービス | Alpenglow Tek',
    '臻至科技致力於提供高品質且具競爭力的 ASIC 設計服務，協助客戶將創新構想轉化為可量產的半導體產品。無論是低功耗邊緣 AI SoC 或客製化專用晶片，我們都能提供專業且可靠的技術支援。': 'Alpenglow Tekは高品質で競争力のあるASIC設計サービスを提供し、お客様の革新的なアイデアを量産可能な半導体製品に変換する支援に取り組んでいます。低消費電力エッジAI SoCであれ、カスタム専用チップであれ、私たちは専門的で信頼性の高い技術サポートを提供します。',
    '客製化 ASIC 設計服務': 'カスタムASIC設計サービス',
    '從架構規劃到系統驗證的一站式晶片開發解決方案': 'アーキテクチャ計画からシステム検証までのワンストップチップ開発ソリューション',
    '臻至科技提供專業的客製化 ASIC 設計服務，涵蓋從規格定義、RTL 設計、後端實作到系統驗證與量產前準備。我們結合低功耗 AI 加速器技術與完整的 IC 設計流程，協助客戶加速產品開發週期並降低整體開發風險。': 'Alpenglow Tekは、仕様定義、RTL設計、バックエンド実装からシステム検証および量産準備までを網羅する専門的なカスタムASIC設計サービスを提供します。低消費電力AIアクセラレータ技術と完全なIC設計フローを組み合わせることで、お客様の製品開発サイクルの短縮と全体的な開発リスクの軽減を支援します。',
    '服務項目': 'サービス内容',
    '與客戶共同定義產品規格、系統架構與 IP 策略，確立設計目標與開發路徑。': 'お客様と共同で製品仕様、システムアーキテクチャ、IP戦略を定義し、設計目標と開発パスを確立します。',
    'ASIC / IP 設計服務': 'ASIC / IP 設計サービス',
    '提供完整的 RTL 設計與驗證服務，並進行邏輯合成與實體設計實作，確保設計品質與時程掌控。': '完全なRTL設計および検証サービスを提供し、論理合成と物理設計の実装を行い、設計の品質とスケジュールの管理を確保します。',
    'AI 加速前端資料處理層': 'AIアクセラレーションフロントエンドデータ処理層',
    '結合 ANIX NPU IP 與低功耗架構技術，協助客戶打造具競爭力的邊緣 AI SoC。': 'ANIX NPU IPと低消費電力アーキテクチャ技術を組み合わせ、お客様が競争力のあるエッジAI SoCを構築できるよう支援します。',
    'FPGA 原型驗證': 'FPGAプロトタイピング',
    '透過 FPGA 原型驗證與系統 Bring-up，縮短開發週期並提升流片成功率。': 'FPGAプロトタイピングとシステムBring-upにより、開発サイクルを短縮し、テープアウトの成功率を向上させます。',
    'SoM 與原型驗證設計': 'SoMとプロトタイピング設計',
    '提供 EVB 設計、System Bring-up 與晶片驗證服務，協助客戶完成產品化與量產前準備。': 'EVB設計、システムBring-up、およびチップ検証サービスを提供し、お客様の製品化と量産準備の完了を支援します。',
    '我們提供從需求規劃到系統驗證的一站式 ASIC 開發服務，確保設計品質與時程可控，並協助客戶順利完成從概念到量產的晶片開發。': '私たちは要件計画からシステム検証までのワンストップASIC開発サービスを提供し、設計の品質と管理可能なスケジュールを確保し、概念から量産までのチップ開発を円滑に完了できるようお客様を支援します。',
    '核心優勢': 'コアの優位性',
    '超低功耗 AI 晶片專業能力': '超低消費電力AIチップの専門知識',
    '從架構設計到晶片實現，具備全流程經驗，能兼顧技術深度與產品落地需求。': 'アーキテクチャ設計からチップの実現まで、フルプロセスの経験を持ち、技術の深さと製品の展開ニーズのバランスを取ることができます。',
    '完整 ASIC 設計流程': '完全なASIC設計フロー',
    '降低開發風險並加速產品上市': '開発リスクを軽減し、市場投入までの時間を短縮',
    '彈性合作與 IP 整合能力': '柔軟な協力とIP統合能力',
    '支援客戶自有 IP 或第三方 IP 整合，並提供客製化設計與技術顧問服務。': 'お客様独自のIPやサードパーティ製IPの統合をサポートし、カスタム設計および技術コンサルティングサービスを提供します。',
    '為客戶打造高效且可靠的晶片開發流程': 'お客様のために効率的で信頼性の高いチップ開発ワークフローを構築',
    '客製化 ASIC 應用領域': 'カスタムASICの応用分野',
    '客製化 ASIC': 'カスタムASIC',
    '專業的 ASIC 與矽智財 (IP) 設計服務': '専門的なASICおよびIP設計サービス',
    '縮短設計開發與量產時程': '設計、開発、量産のスケジュールを短縮',

    # FPGA PQC, FPGA Event Camera, FPGA RF, FPGA Preprocess
    'FPGA — 事件相機': 'FPGA — イベントカメラ',
    '事件相機：影像辨識解決方案 | FPGA | 臻至科技 Alpenglow Tek': 'イベントカメラ：画像認識ソリューション | FPGA | Alpenglow Tek',
    '臻至科技結合事件相機系統整合能力與 FPGA 硬體加速技術，為高速感知與即時運算場景提供低延遲、高吞吐與低功耗的專業解決方案。': 'Alpenglow Tekは、イベントカメラシステム統合能力とFPGAハードウェアアクセラレーション技術を組み合わせ、高速認識およびリアルタイムコンピューティングシナリオに低遅延、高スループット、低消費電力の専門ソリューションを提供します。',
    '事件相機：影像辨識解決方案': 'イベントカメラ：画像認識ソリューション',
    '讓高速動態世界，真正被即時捕捉': '高速でダイナミックな世界を、真にリアルタイムで捉える',
    '事件相機（Event-based Camera）是一種不同於傳統 RGB 相機的新型感測技術。': 'イベントベースカメラは、従来のRGBカメラとは異なる斬新なセンシング技術です。',
    '結合 FPGA 的強大平行處理與極低延遲特性，為邊緣 AI、機器人與高速工業檢測帶來革命性的感知能力。': 'FPGAの強力な並列処理と極めて低い遅延特性を組み合わせ、エッジAI、ロボティクス、高速産業検査に革命的な認識能力をもたらします。',
    '什麼是事件相機？': 'イベントカメラとは？',
    '傳統相機以固定幀率（例如\n                            30fps、60fps）持續擷取完整畫面，即使畫面中沒有變化，也會重複記錄大量冗餘資訊。而事件相機則採用「非同步事件驅動」機制，只有在畫素亮度發生變化時才輸出事件資料。': '従来のカメラは、固定フレームレート（例：30fps、60fps）で完全なフレームを継続的にキャプチャし、変化がない場合でも大量の冗長情報を繰り返し記録します。対照的に、イベントカメラは「非同期イベント駆動」メカニズムを採用し、ピクセルの明るさが変化したときにのみイベントデータを出力します。',
    '這種機制帶來三項關鍵特性：': 'このメカニズムは3つの重要な特性をもたらします：',
    '超低延遲反應': '超低遅延応答',
    '極高動態範圍': '極めて高いダイナミックレンジ',
    '低冗餘輸出': '低冗長出力',
    '微秒等級即時輸出': 'マイクロ秒レベルのリアルタイム出力',
    'Microsecond 等級的反應速度，遠超傳統幀率相機，適合需要即時感知的高速場景應用。': 'マイクロ秒レベルの応答速度は、従来のフレームレートカメラをはるかに凌駕し、リアルタイムの認識を必要とする高速シナリオのアプリケーションに適しています。',
    '動態範圍可達 120dB 以上，即使在強光或極暗環境下，也能穩定捕捉關鍵影像資訊。': '120dB以上のダイナミックレンジにより、強い光や極端に暗い環境下でも、重要な画像情報を安定して捉えることができます。',
    '僅在畫素亮度發生變化時輸出資料，大幅減少冗餘資訊，降低後端處理負擔。': 'ピクセルの明るさが変化したときにのみデータを出力し、冗長情報を大幅に削減して、バックエンドの処理負荷を軽減します。',
    '為什麼事件相機必須搭配 FPGA？': 'なぜイベントカメラにはFPGAが必要なのか？',
    '事件相機輸出的資料並非傳統的二維矩陣影像，而是連續且非同步的「事件流」（Event Stream）。這類資料在處理時具有極高的吞吐量與嚴苛的即時性要求。': 'イベントカメラが出力するデータは、従来の2Dマトリクス画像ではなく、連続的で非同期な「イベントストリーム」です。この種のデータを処理するには、極めて高いスループットと厳しいリアルタイム要件が求められます。',
    '如果將事件流直接交由 CPU 或 GPU 處理，會面臨以下瓶頸：': 'イベントストリームをCPUやGPUで直接処理する場合、以下のボトルネックに直面します：',
    '中斷負載過高': '過剰な割り込み負荷',
    '記憶體頻寬瓶頸': 'メモリ帯域幅のボトルネック',
    '峰值吞吐量不足': 'ピークスループットの不足',
    '臻至科技的 FPGA 事件處理解決方案': 'Alpenglow TekのFPGAイベント処理ソリューション',
    '透過專用硬體資料路徑設計與高速事件流處理架構，我們成功實現微秒等級延遲反應與高吞吐穩定運作能力。': '専用のハードウェアデータパス設計と高速イベントストリーム処理アーキテクチャを通じて、マイクロ秒レベルの遅延応答と高スループットの安定動作能力の実現に成功しました。',
    '高吞吐事件分析': '高スループットイベント分析',
    '支援高速介面（PCIe、JESD204B/C、100GbE）': '高速インターフェース（PCIe、JESD204B/C、100GbE）をサポート',
    '極低延遲前處理能力': '超低遅延前処理能力',
    '邊緣偵測與特徵提取': 'エッジ検出と特徴抽出',
    '光流 (Optical Flow) 與目標追蹤': 'オプティカルフローとターゲットトラッキング',
    '客製化 AI 感知加速模組': 'カスタマイズされたAI認識アクセラレーションモジュール',
    '與傳統 RGB 相機的差異': '従来のRGBカメラとの違い',
    '比較項目': '比較項目',
    '傳統 RGB 相機': '従来のRGBカメラ',
    '資料輸出': 'データ出力',
    '固定幀率完整畫面': '固定フレームレートでのフルフレーム',
    '僅輸出變化事件': '変化したイベントのみを出力',
    '延遲': '遅延',
    '受限於幀率': 'フレームレートに制限される',
    '極低': '極めて低い',
    '動態範圍': 'ダイナミックレンジ',
    '有限': '限定的',
    '極高': '極めて高い',
    '資料量': 'データ量',
    '大量畫面資料': '大量の画像データ',
    '相較之下較低': '比較的少ない',
    '極端光照': '極端な照明',
    '容易過曝或欠曝': '露出過多または露出不足になりやすい',
    '可應對極端光照': '極端な照明にも対応可能',
    '事件相機的產業應用': 'イベントカメラの産業応用',
    '根據國際事件視覺技術發展趨勢，事件相機已廣泛應用於以下領域：': '国際的なイベントビジョン技術の発展傾向によれば、イベントカメラは以下の分野で広く適用されています：',
    '機器人與無人載具': 'ロボティクスと無人搬送車',
    '事件相機反應延遲低於 1ms，使機器人能在動態環境中做出即時判斷。': '1ms未満のイベントカメラの応答遅延により、ロボットは動的な環境でリアルタイムの判断を下すことができます。',
    '視覺導航與即時避障': '視覚ナビゲーションとリアルタイム障害物回避',
    '高速動作捕捉與追蹤': '高速モーションキャプチャとトラッキング',
    '機械手臂精準定位與反應控制': 'ロボットアームの精密な位置決めと応答制御',
    '工業自動化與智慧製造': '産業オートメーションとスマートマニュファクチャリング',
    '超低延遲結合高動態範圍，可應對工業環境中的強光、陰影與高速運動挑戰。': '超低遅延と高ダイナミックレンジの組み合わせにより、産業環境における強い光、影、高速運動の課題に対処できます。',
    '高速生產線瑕疵即時偵測': '高速生産ラインのリアルタイム欠陥検出',
    '高速旋轉元件與振動分析': '高速回転部品と振動分析',
    '晶片與電路板外觀檢驗': 'チップと回路基板の外観検査',
    '車用電子與智慧運輸': '車載エレクトロニクスとスマート交通',
    '微秒級反應與高動態範圍感知，為智慧駕駛與 V2X 系統提供可靠的即時視覺支援。': 'マイクロ秒レベルの応答と高ダイナミックレンジの認識により、スマートドライビングとV2Xシステムに信頼性の高いリアルタイムの視覚的サポートを提供します。',
    'ADAS 視覺感知前處理': 'ADAS視覚認識前処理',
    '駕駛員行為即時分析': 'リアルタイムのドライバーの行動分析',
    '高速道路目標偵測與追蹤': '高速道路のターゲット検出とトラッキング',
    '智慧監控與安全應用': 'スマート監視とセキュリティ応用',
    '結合 FPGA 即時處理能力，事件相機可實現全天候監控與高可靠度國防感知。': 'FPGAのリアルタイム処理能力と組み合わせることで、イベントカメラは全天候型の監視と高信頼性の防衛認識を実現します。',
    '低功耗長時間夜視監控': '低消費電力・長時間の暗視監視',
    '邊境感知與無人機反制系統': '国境の認識と対ドローンシステム',
    '夜間與惡劣天氣感知輔助': '夜間および悪天候時の認識支援',
    '臻至科技已完成事件相機與 FPGA 平台之整合與即時處理驗證。': 'Alpenglow Tekは、イベントカメラとFPGAプラットフォームの統合およびリアルタイム処理検証を完了しました。',
    '下方影片展示實際系統運行與事件處理成果。': '下のビデオは、実際のシステム操作とイベント処理の結果を示しています。',
    '展示事件相機與 FPGA 系統整合之實際運作成果': 'イベントカメラとFPGAシステムの統合の実際の動作結果を紹介',
    '與我們合作，打造下一代智慧晶片': '私たちと協力して、次世代のスマートチップを構築する',
    
    'FPGA — 視覺/聽覺前處理': 'FPGA — 視覚/聴覚前処理',
    'FPGA – 視覺與聽覺前處理加速解決方案 | 臻至科技 Alpenglow Tek': 'FPGA – 視覚および聴覚前処理アクセラレーションソリューション | Alpenglow Tek',
    '為即時 AI 感知系統打造高速前處理核心': 'リアルタイムAI認識システム向けの高速前処理コアの構築',
    '臻至科技提供基於 FPGA 的視覺與聽覺前處理解決方案，透過硬體級平行運算與可重構架構，加速影像與聲音資料在進入 AI 模型前的關鍵處理流程。此技術能大幅降低系統延遲並提升運算效率，廣泛應用於機器人、自主移動載具、智慧監控、語音互動裝置與邊緣 AI 感知系統。': 'Alpenglow TekはFPGAベースの視覚および聴覚前処理ソリューションを提供し、ハードウェアレベルの並列コンピューティングと再構成可能なアーキテクチャを通じて、画像データと音声データがAIモデルに入る前の重要な処理フローを加速します。この技術はシステムの遅延を大幅に削減し、計算効率を向上させ、ロボット、AMR、スマート監視、音声対話デバイス、およびエッジAI認識システムで広く使用されています。',
    '為什麼 AI 感知系統需要 FPGA 前處理？': 'なぜAI認識システムにはFPGA前処理が必要なのか？',
    '在 AI 視覺與聽覺應用中，大量時間與運算資源消耗於資料前處理階段，例如影像轉換、降噪、特徵提取與訊號轉換。若僅依賴 CPU 或 GPU 進行處理，容易產生延遲與功耗瓶頸，影響即時反應能力。FPGA 能透過硬體平行化與管線化設計，在資料進入 AI 模型之前完成即時前處理，顯著降低延遲並提升整體系統效能。': 'AIの視覚および聴覚アプリケーションでは、画像変換、ノイズリダクション、特徴抽出、信号変換などのデータ前処理段階で、大量の時間と計算リソースが消費されます。CPUやGPUのみに依存して処理を行うと、遅延や消費電力のボトルネックが生じやすく、リアルタイムの応答能力に影響を与えます。FPGAはハードウェアの並列化とパイプライン設計を通じて、データがAIモデルに入る前にリアルタイムの前処理を完了し、遅延を大幅に削減してシステム全体のパフォーマンスを向上させます。',
    '影像擷取與格式轉換 (RAW、YUV、RGB)': '画像キャプチャとフォーマット変換（RAW、YUV、RGB）',
    '影像縮放與幾何校正': '画像スケーリングと幾何学補正',
    '去噪與影像增強 (Denoise、HDR)': 'ノイズ除去と画像強調（Denoise、HDR）',
    '聽覺前處理技術': '聴覚前処理技術',
    '語音擷取與降噪處理': '音声キャプチャとノイズ除去',
    '回聲消除 (AEC) 與波束成形 (Beamforming)': '音響エコーキャンセレーション（AEC）とビームフォーミング',
    'FFT／頻譜分析與特徵提取 (MFCC)': 'FFT / スペクトル分析と特徴抽出 (MFCC)',
    '聲源定位 (Sound Source Localization)': '音源定位',
    '語音活動偵測 (VAD)': '音声活動検出（VAD）',
    '降低主處理器負載': 'メインプロセッサの負荷を軽減',
    'AI 前處理管線設計與優化': 'AI前処理パイプラインの設計と最適化',
    '感測器介面整合 (Camera / Microphone)': 'センサーインターフェースの統合（カメラ/マイク）',
    '邊緣 AI 落地場景': 'エッジAIの実装シナリオ',
    '自主移動機器人 (AMR) 與服務型機器人': '自律移動ロボット（AMR）とサービスロボット',
    '多感測器融合與低延遲感知': 'マルチセンサーフュージョンと低遅延認識',
    '即時影像分析與目標辨識': 'リアルタイム画像分析とターゲット認識',
    '語音互動與人機協作': '音声インタラクションと人間と機械の協調',
    '以極低延遲的硬體加速，打造即時 AI 感知系統': '超低遅延のハードウェアアクセラレーションを備えたリアルタイムAI認識システムの構築',
    
    'FPGA — PQC 密碼學': 'FPGA — PQC暗号学',
    '透過平行化資料路徑與管線化設計，大幅降低加解密延遲並提升系統整體吞吐量，適用於即時安全通訊與高效能應用。': '並列化されたデータパスとパイプライン設計により、暗号化/復号化の遅延を大幅に削減し、システム全体のスループットを向上させ、リアルタイムの安全な通信と高性能アプリケーションに適しています。',
    '高安全數位簽章、身分驗證與交易保護。': '高セキュリティのデジタル署名、身元確認、トランザクション保護。',
    '支援演算法更新與標準演進，當 PQC 標準持續發展時，可透過重新配置 FPGA 快速升級，降低系統風險與維運成本。': 'アルゴリズムの更新と標準の進化をサポートし、PQC標準が発展し続ける中、FPGAの再構成による迅速なアップグレードが可能であり、システムリスクと保守コストを削減します。',
    '針對 PQC 演算法中的多項式運算、模數運算與 NTT（Number Theoretic Transform）進行專用硬體優化，顯著提升運算效率。': 'PQCアルゴリズムにおける多項式演算、モジュラ演算、NTT（数論変換）のための専用ハードウェア最適化により、計算効率が大幅に向上します。',
    'PQC 演算法（如 CRYSTALS-Kyber、CRYSTALS-Dilithium 等）具有高度運算密集與記憶體存取需求，若在傳統 CPU 或 GPU 上執行，往往面臨延遲高、功耗大與效率不足等問題。由於 CPU 與 GPU 的硬體架構固定且通用性高，難以針對特定密碼學運算進行最佳化。': 'PQCアルゴリズム（CRYSTALS-Kyber、CRYSTALS-Dilithiumなど）は、計算集約型であり、メモリアクセスの要求が高くなっています。従来のCPUやGPUでこれらを実行すると、遅延が高く、消費電力が大きく、効率が不十分であるという問題に直面することがよくあります。CPUおよびGPUのハードウェアアーキテクチャは固定されており、汎用性が高いため、特定の暗号操作に合わせて最適化することは困難です。',
    '相較之下，FPGA 具備可重組（Reconfigurable）特性，可依據 PQC 演算法需求客製化硬體架構，透過高度平行化運算與專用資料通道設計，在更低的資源使用下實現更低的延遲與更低的功耗，並兼具靈活性與可升級能力。': '対照的に、FPGAは再構成可能（Reconfigurable）な特性を備えており、PQCアルゴリズムの要件に基づいてハードウェアアーキテクチャをカスタマイズできます。高度に並列化された計算と専用のデータパス設計により、より少ないリソース使用でより低い遅延と消費電力を実現し、柔軟性とアップグレード可能性を兼ね備えています。',
    '透過實際 FPGA 平台展示，我們呈現後量子密碼學演算法的硬體加速成果與系統整合能力，展現高效能、低延遲與低功耗的技術優勢。': '実際のFPGAプラットフォームのデモンストレーションを通じて、ポスト量子暗号アルゴリズムのハードウェアアクセラレーションの成果とシステム統合機能を紹介し、高性能、低遅延、低消費電力という技術的優位性を示します。',
    '探索臻至科技在後量子密碼學硬體加速領域的技術成果與實際系統驗證': 'ポスト量子暗号ハードウェアアクセラレーションの分野におけるAlpenglow Tekの技術的成果と実際のシステム検証を探る',
    
    'FPGA — RF 射頻': 'FPGA — RF無線周波数',
    'FPGA – RF 射頻高速訊號處理解決方案 | 臻至科技 Alpenglow Tek': 'FPGA – RF高速信号処理ソリューション | Alpenglow Tek',
    '臻至科技提供基於 FPGA 的 RF 射頻訊號處理解決方案，即時處理高速、高頻寬的無線訊號，廣泛應用於 5G/6G 通訊、雷達系統、衛星通訊與電子戰設備。': 'Alpenglow TekはFPGAベースのRF信号処理ソリューションを提供し、高速・高帯域幅の無線信号をリアルタイムで処理し、5G/6G通信、レーダーシステム、衛星通信、電子戦機器で広く使用されています。',
    '為新世代無線通訊打造高效能 RF 訊號處理核心': '次世代無線通信向けの高性能RF信号処理コアの構築',
    '臻至科技提供基於 FPGA 的 RF 射頻訊號處理解決方案，能即時處理高速、高頻寬的無線訊號，廣泛應用於 5G/6G 通訊、雷達系統、衛星通訊與電子戰設備，協助客戶實現高效能、低延遲與高度彈性的系統設計。': 'Alpenglow Tekは、高速で高帯域幅の無線信号をリアルタイムで処理できるFPGAベースのRF信号処理ソリューションを提供します。これらのソリューションは、5G/6G通信、レーダーシステム、衛星通信、電子戦機器で広く使用されており、お客様が高性能、低遅延、柔軟性の高いシステム設計を実現できるよう支援します。',
    '為什麼 RF 射頻系統需要 FPGA？': 'なぜRFシステムにはFPGAが必要なのか？',
    'RF 射頻系統需處理高速、高頻寬且即時性的資料流，對延遲、吞吐量與運算效率要求極高。': 'RFシステムは、高速で高帯域幅のリアルタイムデータストリームを処理する必要があり、遅延、スループット、および計算効率に対して極めて高い要求があります。',
    'FPGA 憑藉其可重構與高度平行化架構，成為 RF 與無線通訊系統的理想運算平台。': 'FPGAは、その再構成可能で高度に並列化されたアーキテクチャにより、RFおよび無線通信システムの理想的なコンピューティングプラットフォームとなっています。',
    'CPU/GPU vs. FPGA：RF 訊號處理平台比較': 'CPU/GPU vs. FPGA: RF信号処理プラットフォームの比較',
    '即時處理能力': 'リアルタイム処理能力',
    '中斷負載過高，延遲較高': '割り込み負荷が高すぎる、遅延が高い',
    '硬體級即時處理能力': 'ハードウェアレベルのリアルタイム処理能力',
    '平行處理能力': '並列処理能力',
    '受限於核心數量': 'コアの数に制限される',
    '高度平行化運算架構': '高度に並列化された計算アーキテクチャ',
    '功耗效率': '電力効率',
    '較高': '高い',
    '較低': '低い',
    '可客製化程度': 'カスタマイズ性',
    '無': 'なし',
    '有': 'あり',
    '臻至科技 FPGA RF 射頻訊號處理解決方案': 'Alpenglow Tek FPGA RF信号処理ソリューション',
    'RF 數位前端（DFE）設計': 'RFデジタルフロントエンド（DFE）設計',
    '數位下變頻（DDC）與上變頻（DUC）': 'デジタルダウンコンバージョン（DDC）とアップコンバージョン（DUC）',
    '數位濾波器設計（FIR / CIC）': 'デジタルフィルタ設計（FIR / CIC）',
    'FPGA 頻譜分析與訊號處理': 'FPGAスペクトル分析と信号処理',
    'FFT / IFFT 頻譜分析': 'FFT / IFFTスペクトル分析',
    '調變與解調技術': '変調と復調技術',
    '雷達訊號處理加速': 'レーダー信号処理のアクセラレーション',
    '多通道同步處理': 'マルチチャネル同期処理',
    '適用於 SDR（Software-Defined Radio）': 'SDR（ソフトウェア定義無線）に適しています',
    'SDR 平台開發與客製化': 'SDRプラットフォームの開発とカスタマイズ',
    'FPGA 解碼平行處理': 'FPGAデコードの並列処理',
    '5G/6G 與無線通訊': '5G/6Gと無線通信',
    '基地台與小型基地台': '基地局とスモールセル',
    'Open RAN 架構': 'Open RANアーキテクチャ',
    'Massive MIMO 與 Beamforming': 'Massive MIMOとビームフォーミング',
    '無線回傳與前傳': 'ワイヤレスバックホールとフロントホール',
    '雷達與感測系統': 'レーダーとセンシングシステム',
    '車用毫米波雷達': '車載用ミリ波レーダー',
    '國防雷達與電子戰': '防衛レーダーと電子戦',
    '無人機與航太感測': 'ドローンと航空宇宙センシング',
    '衛星與航太通訊': '衛星と航空宇宙通信',
    '低軌道衛星（LEO）': '低軌道（LEO）衛星',
    '衛星地面站': '衛星地上局',
    '深空通訊': '深宇宙通信',
    '測試與量測設備': 'テストおよび測定機器',
    '頻譜分析儀': 'スペクトラムアナライザ',
    '訊號產生器': '信号発生器',
    'EMI/EMC 測試系統': 'EMI/EMCテストシステム',
    'RF 測試平台': 'RFテストプラットフォーム',
    '為新世代無線通訊與雷達系統提供高效能、低延遲的可重構運算平台': '次世代の無線通信およびレーダーシステム向けに、高性能で低遅延の再構成可能なコンピューティングプラットフォームを提供',
    '在無線通訊與雷達系統中，產品競爭的關鍵不僅在於頻寬與運算能力，更在於即時性、可靠度與系統彈性。臻至科技透過 FPGA 可重構運算架構與高速數位訊號處理技術，提供低延遲、高吞吐與高可靠度的 RF 射頻解決方案，協助客戶加速產品開發並實現新世代通訊與感測系統的創新應用。': '無線通信およびレーダーシステムにおいて、製品の競争力は帯域幅や計算能力だけでなく、リアルタイム性、信頼性、システムの柔軟性にも依存します。Alpenglow Tekは、FPGAの再構成可能なコンピューティングアーキテクチャと高速デジタル信号処理技術を通じて、低遅延、高スループット、高信頼性のRFソリューションを提供し、お客様が製品開発を加速し、次世代の通信およびセンシングシステムで革新的なアプリケーションを実現できるよう支援します。',
    '臻至科技具備高速數位訊號處理與 FPGA 設計專業，提供完整的 RF 射頻訊號處理解決方案，協助客戶快速實現高效能無線通訊與雷達系統。': 'Alpenglow Tekは、高速デジタル信号処理とFPGA設計の専門知識を持ち、完全なRF信号処理ソリューションを提供して、お客様が高性能の無線通信およびレーダーシステムを迅速に実装できるよう支援します。',

    # News
    '掌握臻至科技的最新動態與媒體報導，我們致力於超低功耗邊緣 AI 運算技術創新。': 'Alpenglow Tekの最新ニュースとメディアの報道をご覧ください。私たちは超低消費電力エッジAIコンピューティング技術の革新を推進しています。',
    '第二屆「智慧創新大賞」百大贏家出爐': '第2回「スマートイノベーションアワード」のトップ100受賞者が発表されました',
    '經濟部 產業技術司': '経済部 産業技術司',
    '國立台灣大學 TEC': '国立台湾大学 TEC',
    '國家高速網路與計算中心': '国家高速ネットワーク・計算センター',
    '新北市青年局-新北創力坊': '新北市青年局 - InnoSquare',
    '延伸閱讀': '関連記事',

    # Team
    '擁有 20 年以上業界產品經驗，專注於領導企業在 IC 設計領域的創新發展，並推動公司在高效能計算及自訂硬體加速解決方案方面的佈局': '20年以上の業界製品経験を持ち、IC設計分野における企業の革新的な発展を主導し、高性能コンピューティングおよびカスタムハードウェアアクセラレーションソリューションの分野で会社の展開を推進することに注力しています。',
    '專注於客戶關係維護與業務拓展，負責FPGA IP授權、技術服務合約談判，開拓新市場機會，並推動產官學合作與策略夥伴關係發展': '顧客関係の維持と事業拡大に焦点を当て、FPGA IPライセンス、技術サービス契約の交渉、新しい市場機会の開拓を担当し、産官学連携と戦略的パートナーシップの発展を推進しています。',
    '擁有深厚業界IC設計專案經驗、多項硬體加速器專利與頂尖論壇發表論文，專注於硬體加速和嵌入式系統設計，領導團隊在硬體加速領域的持續創新與優化': '深い業界でのIC設計プロジェクト経験、複数のハードウェアアクセラレータ特許、およびトップフォーラムで発表された論文を持ちます。ハードウェアアクセラレーションと組み込みシステム設計に注力し、ハードウェアアクセラレーション分野におけるチームの継続的な革新と最適化をリードしています。',
    '專注於系統性能優化與維護，並協助設計與實現 ASIC 解決方案，確保產品在硬體層面的穩定性、高效能與整體整合品質。': 'システムのパフォーマンス最適化と保守に焦点を当て、ASICソリューションの設計と実装を支援し、ハードウェアレベルでの製品の安定性、高性能、および全体的な統合品質を確保します。',
    '負責分析市場數據、產業趨勢與競品動態，根據研究結果提出策略建議，並參與投資評估、合作洽談、商務開發及相關商業決策。': '市場データ、業界のトレンド、競合の動向の分析を担当し、調査結果に基づいて戦略的提案を行い、投資評価、協力交渉、事業開発、および関連するビジネス上の意思決定に参加します。',
    '團隊來自頂尖電資與商管系所，並具備 IC 設計、系統架構與 AI 應用領域的實務經驗，涵蓋從演算法理解、硬體架構設計到晶片實現與系統整合的完整能力。': 'チームは、トップクラスの電気工学、コンピュータサイエンス、および経営管理の学部から集まり、IC設計、システムアーキテクチャ、およびAIアプリケーション分野での実務経験を持っています。アルゴリズムの理解やハードウェアアーキテクチャの設計からチップの実装やシステム統合に至るまでの完全な能力を網羅しています。',
    '從架構設計到晶片實現，具備全流程經驗，能兼顧技術深度與產品落地需求。': 'アーキテクチャ設計からチップの実現まで、フルプロセスの経験を持ち、技術の深さと製品の展開ニーズのバランスを取ることができます。',
    '結合工程、系統與市場能力，讓技術開發與應用拓展能同步前進。': 'エンジニアリング、システム、および市場の能力を組み合わせることで、技術開発とアプリケーションの拡大を同時に進めることができます。',
    '我們相信，好的技術來自跨領域的協作、開放的討論與彼此信任。在專業分工之外，我們也重視平等交流與共同成長，持續打造一支能面對挑戰、也能一起前進的團隊。': '優れた技術は、分野を超えたコラボレーション、オープンな議論、そして相互の信頼から生まれると信じています。専門的な分業を超えて、私たちは平等なコミュニケーションと相互の成長を重視し、困難に立ち向かい、共に前進できるチームを継続的に構築しています。'
}

def apply_translations(dir_path, t_map):
    for root, dirs, files in os.walk(dir_path):
        for file in files:
            if file.endswith('.html'):
                filepath = os.path.join(root, file)
                with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                # Replace longer strings first
                for k in sorted(t_map.keys(), key=len, reverse=True):
                    content = content.replace(k, t_map[k])
                
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)

print("Applying English translations...")
apply_translations('en', en_dict)
print("Applying Japanese translations...")
apply_translations('ja', ja_dict)

print("Done!")
